import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link"; // Import Link

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-gray-100 min-h-screen`}
      >
        <header className="bg-gray-800 text-white p-4 shadow-md">
          <nav>
            <ul className="flex space-x-4">
              <li>
                <Link href="/" className="px-3 py-2 rounded-md text-sm font-medium hover:text-gray-300">
                  Home
                </Link>
              </li>
              <li>
                <Link href="/login" className="px-3 py-2 rounded-md text-sm font-medium hover:text-gray-300">
                  Login
                </Link>
              </li>
              <li>
                <Link href="/register" className="px-3 py-2 rounded-md text-sm font-medium hover:text-gray-300">
                  Register
                </Link>
              </li>
              <li>
                <Link href="/dashboard" className="px-3 py-2 rounded-md text-sm font-medium hover:text-gray-300">
                  Dashboard
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <main className="p-4">{children}</main>
      </body>
    </html>
  );
}
