import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Removed Link import as Navbar handles its own links
import { AuthProvider } from "../context/AuthContext"; // Import AuthProvider
import Navbar from "../components/Navbar"; // Import the new Navbar component

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans bg-gray-100 min-h-screen`}
      >
        <AuthProvider>
          <header className="bg-gray-800 text-white p-4 shadow-md">
            <Navbar /> {/* Use the Navbar component here */}
          </header>
          <main className="p-4">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
